### ISSUE TITLE
Adding printing instructions

### ISSUE THREAD

**Issue by willwade** [AceCentre/SpeakBook#12]
I need to add a second page - printing-instructions.html to the speakbook project.

Its much simpler than the more complex index page. I think this will be straightforward markdown. But how would we do it - and add it to the buildpdf buildchain?

See [here](https://acecentre.org.uk/wp-content/uploads/2018/11/Printing-Instructions1.pdf) for the kind of thing we need to create. 

NB: I don't think we will bother to use POEditor strings for a lot of this. Its a lot of text. Maybe some parts like "Speakbook" and URL - but I can't see what else

**Comment by hosseinamin** [comment]
I see, We have to create a layout for regular pdf pages.
