### ISSUE TITLE
SPELL page 7 - needs to be a 'mirror' of page 6, not a duplicate as it is now

### ISSUE THREAD

**Issue by michaelritson** [AceCentre/SpeakBook#34]
The boxes **and their contents** on the left side of page 7 (as printed and bound at the top) and the boxes on the right side need transposing, so that they are a mirror image of the layout of page 6. Page 7 should appear as the original below:
![Speak book page 7 as original](https://user-images.githubusercontent.com/65653315/99965034-2e46df00-2d8c-11eb-932e-4775f9cd6198.JPG)
As in the video here: 
https://vimeo.com/25812980#t=2m22s
The contents of **all** the boxes need their first and third columns transposing, as per the above image - letter colours should be as above image too.

**Comment by willwade** [comment]
@michaelritson  - please take a *very* good look at the English version now. I *think* this is fixed for English

**Comment by willwade** [comment]
So again. Just leaving this open for @hosseinamin to help find a way of making the change occur across all languages
