### ISSUE TITLE
Colour Blind Friendly SPELL page 7

### ISSUE THREAD

**Issue by michaelritson** [AceCentre/SpeakBook#36]
**Blue and Green** boxes (both on right side of page when in landscape) and 
**Pink and Green** boxes (both on left side of page when in landscape) need to be swapped, as image below:
![Page 7 Final Colour Layout](https://user-images.githubusercontent.com/65653315/100754346-e6a30180-33e2-11eb-92a9-738f1487ebe6.JPG)
**Contents of all boxes:** both characters in outer two columns (when viewed in landscape) need to swap sides, all character colours should remain the same, just positions of characters should change, as image above:

**Comment by willwade** [comment]
Think this largely got fixed in https://github.com/AceCentre/SpeakBook/commit/9472bf2b340c24977cd355ed896c70de18314c8d - @michaelritson - can you just check https://speakbook.netlify.app/speakbook/colour.html - and see if that's right?

**Comment by michaelritson** [comment]
Looks good to me! 👍

**Comment by willwade** [comment]
So just leaving this for @hosseinamin as now need a way of replicating this across all other languages

**Comment by hosseinamin** [comment]
@willwade Got it
