### ISSUE TITLE
writing in boxes, Red on tab

### ISSUE THREAD

**Issue by willwade** [AceCentre/SpeakBook#7]
Swedish version:
P8, P9: The numbers, plus sign and KLAR need adding into the boxes, also the yellow blank tab needs changing to a red one which reads 123:

P8:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/229352/81592160-6d47b100-93b5-11ea-8e77-405577050937.png">

P9:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/229352/81592103-543f0000-93b5-11ea-9dd4-bb58ba414e0d.png">

**Comment by hosseinamin** [comment]
Do you mean the rows on these tables should have input fields in them?

**Comment by willwade** [comment]
No. Just centre aligned text. But just in Swedish version. Klar, 1 2 3 4 etc. See the image on the left above.

**Comment by hosseinamin** [comment]
fixed, please check
